---
name: Update Docker Image
run-name: Update Docker Image

on:
  workflow_dispatch:

jobs:
  update-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup runner
        run: |
          sudo apt update -qq && \
          DEBIAN_FRONTEND=noninteractive sudo apt install -y j2cli gettext moreutils >/dev/null 2>&1

      - name: Pakackege list
        run: docker run --rm -i --entrypoint dpkg edelux/dns-proxy -l|awk '/^ii/{split($2,a,":");print a[1]","$3}' >package.old

      - name: New Package
        run: |
          PKGS=$(awk -F, '{printf $1" "}' package.old)
          export PKGS
          echo $PKGS
          j2 script.j2 -o script.sh
          cat script.sh
          docker run --rm -i -v $PWD:/workspace -w /workspace debian:testing sh script.sh

      - name: Show update
        run: awk -F, 'FNR==NR {map[$1]=$2; next} map[$1]!=$2 {print $1","map[$1]}' package.new package.old
...
