---
name: Update Docker Image
run-name: Update Docker Image

on:
  workflow_dispatch:

jobs:
  update-image:
    runs-on: ubuntu-latest

    steps:
      - name: Setup runner
        run: |
          sudo apt update -qq && \
          DEBIAN_FRONTEND=noninteractive sudo apt install -y j2cli gettext moreutils >/dev/null 2>&1

      - name: Pakackege list
        run: docker run --rm -i --entrypoint dpkg edelux/dns-proxy -l|awk '/^ii/{split($2,a,":");print a[1]","$3}' >package.old

      - name: New Package
        run: |
          export PKGS=$(awk -F, '{printf $1" "}' package.old)
          j2 script.j2 -o script.sh
          docker run --rm -i debian:testing -v $PWD:/workspace -v /workspace sh script.sh

      - name: Show list
        run: |
          echo "Installed" && cat package.old
          echo "Current"   && cat package.new
...
