---
name: Update Docker Image
run-name: Update Docker Image

on:
  workflow_dispatch:

jobs:
  update-image:
    runs-on: ubuntu-latest

    steps:
      - name: Show Pakackege list
        run: awk -W version
...
